version: '3'
services:
    laravel_project:
        container_name: laravel-app1
        image: 'laravel-app1:${TAG_NAME}'
        environment:
          - TZ=Asia/Dhaka
        ports:
          - "8000:8000"
        restart: always
        build:
            context: "."
            dockerfile: "Dockerfile"
        volumes: 
          - ./data:/app
